/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	volumenfsexportv1 "github.com/kubernetes-csi/external-nfsexporter/client/v6/apis/volumenfsexport/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVolumeNfsExports implements VolumeNfsExportInterface
type FakeVolumeNfsExports struct {
	Fake *FakeNfsExportV1
	ns   string
}

var volumenfsexportsResource = schema.GroupVersionResource{Group: "nfsexport.storage.k8s.io", Version: "v1", Resource: "volumenfsexports"}

var volumenfsexportsKind = schema.GroupVersionKind{Group: "nfsexport.storage.k8s.io", Version: "v1", Kind: "VolumeNfsExport"}

// Get takes name of the volumeNfsExport, and returns the corresponding volumeNfsExport object, and an error if there is any.
func (c *FakeVolumeNfsExports) Get(ctx context.Context, name string, options v1.GetOptions) (result *volumenfsexportv1.VolumeNfsExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(volumenfsexportsResource, c.ns, name), &volumenfsexportv1.VolumeNfsExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*volumenfsexportv1.VolumeNfsExport), err
}

// List takes label and field selectors, and returns the list of VolumeNfsExports that match those selectors.
func (c *FakeVolumeNfsExports) List(ctx context.Context, opts v1.ListOptions) (result *volumenfsexportv1.VolumeNfsExportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(volumenfsexportsResource, volumenfsexportsKind, c.ns, opts), &volumenfsexportv1.VolumeNfsExportList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &volumenfsexportv1.VolumeNfsExportList{ListMeta: obj.(*volumenfsexportv1.VolumeNfsExportList).ListMeta}
	for _, item := range obj.(*volumenfsexportv1.VolumeNfsExportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested volumeNfsExports.
func (c *FakeVolumeNfsExports) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(volumenfsexportsResource, c.ns, opts))

}

// Create takes the representation of a volumeNfsExport and creates it.  Returns the server's representation of the volumeNfsExport, and an error, if there is any.
func (c *FakeVolumeNfsExports) Create(ctx context.Context, volumeNfsExport *volumenfsexportv1.VolumeNfsExport, opts v1.CreateOptions) (result *volumenfsexportv1.VolumeNfsExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(volumenfsexportsResource, c.ns, volumeNfsExport), &volumenfsexportv1.VolumeNfsExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*volumenfsexportv1.VolumeNfsExport), err
}

// Update takes the representation of a volumeNfsExport and updates it. Returns the server's representation of the volumeNfsExport, and an error, if there is any.
func (c *FakeVolumeNfsExports) Update(ctx context.Context, volumeNfsExport *volumenfsexportv1.VolumeNfsExport, opts v1.UpdateOptions) (result *volumenfsexportv1.VolumeNfsExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(volumenfsexportsResource, c.ns, volumeNfsExport), &volumenfsexportv1.VolumeNfsExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*volumenfsexportv1.VolumeNfsExport), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVolumeNfsExports) UpdateStatus(ctx context.Context, volumeNfsExport *volumenfsexportv1.VolumeNfsExport, opts v1.UpdateOptions) (*volumenfsexportv1.VolumeNfsExport, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(volumenfsexportsResource, "status", c.ns, volumeNfsExport), &volumenfsexportv1.VolumeNfsExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*volumenfsexportv1.VolumeNfsExport), err
}

// Delete takes name of the volumeNfsExport and deletes it. Returns an error if one occurs.
func (c *FakeVolumeNfsExports) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(volumenfsexportsResource, c.ns, name, opts), &volumenfsexportv1.VolumeNfsExport{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVolumeNfsExports) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(volumenfsexportsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &volumenfsexportv1.VolumeNfsExportList{})
	return err
}

// Patch applies the patch and returns the patched volumeNfsExport.
func (c *FakeVolumeNfsExports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *volumenfsexportv1.VolumeNfsExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(volumenfsexportsResource, c.ns, name, pt, data, subresources...), &volumenfsexportv1.VolumeNfsExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*volumenfsexportv1.VolumeNfsExport), err
}
