/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	volumenfsexportv1 "github.com/kubernetes-csi/external-nfsexporter/client/v6/apis/volumenfsexport/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVolumeNfsExportContents implements VolumeNfsExportContentInterface
type FakeVolumeNfsExportContents struct {
	Fake *FakeNfsExportV1
}

var volumenfsexportcontentsResource = schema.GroupVersionResource{Group: "nfsexport.storage.k8s.io", Version: "v1", Resource: "volumenfsexportcontents"}

var volumenfsexportcontentsKind = schema.GroupVersionKind{Group: "nfsexport.storage.k8s.io", Version: "v1", Kind: "VolumeNfsExportContent"}

// Get takes name of the volumeNfsExportContent, and returns the corresponding volumeNfsExportContent object, and an error if there is any.
func (c *FakeVolumeNfsExportContents) Get(ctx context.Context, name string, options v1.GetOptions) (result *volumenfsexportv1.VolumeNfsExportContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(volumenfsexportcontentsResource, name), &volumenfsexportv1.VolumeNfsExportContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*volumenfsexportv1.VolumeNfsExportContent), err
}

// List takes label and field selectors, and returns the list of VolumeNfsExportContents that match those selectors.
func (c *FakeVolumeNfsExportContents) List(ctx context.Context, opts v1.ListOptions) (result *volumenfsexportv1.VolumeNfsExportContentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(volumenfsexportcontentsResource, volumenfsexportcontentsKind, opts), &volumenfsexportv1.VolumeNfsExportContentList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &volumenfsexportv1.VolumeNfsExportContentList{ListMeta: obj.(*volumenfsexportv1.VolumeNfsExportContentList).ListMeta}
	for _, item := range obj.(*volumenfsexportv1.VolumeNfsExportContentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested volumeNfsExportContents.
func (c *FakeVolumeNfsExportContents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(volumenfsexportcontentsResource, opts))
}

// Create takes the representation of a volumeNfsExportContent and creates it.  Returns the server's representation of the volumeNfsExportContent, and an error, if there is any.
func (c *FakeVolumeNfsExportContents) Create(ctx context.Context, volumeNfsExportContent *volumenfsexportv1.VolumeNfsExportContent, opts v1.CreateOptions) (result *volumenfsexportv1.VolumeNfsExportContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(volumenfsexportcontentsResource, volumeNfsExportContent), &volumenfsexportv1.VolumeNfsExportContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*volumenfsexportv1.VolumeNfsExportContent), err
}

// Update takes the representation of a volumeNfsExportContent and updates it. Returns the server's representation of the volumeNfsExportContent, and an error, if there is any.
func (c *FakeVolumeNfsExportContents) Update(ctx context.Context, volumeNfsExportContent *volumenfsexportv1.VolumeNfsExportContent, opts v1.UpdateOptions) (result *volumenfsexportv1.VolumeNfsExportContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(volumenfsexportcontentsResource, volumeNfsExportContent), &volumenfsexportv1.VolumeNfsExportContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*volumenfsexportv1.VolumeNfsExportContent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVolumeNfsExportContents) UpdateStatus(ctx context.Context, volumeNfsExportContent *volumenfsexportv1.VolumeNfsExportContent, opts v1.UpdateOptions) (*volumenfsexportv1.VolumeNfsExportContent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(volumenfsexportcontentsResource, "status", volumeNfsExportContent), &volumenfsexportv1.VolumeNfsExportContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*volumenfsexportv1.VolumeNfsExportContent), err
}

// Delete takes name of the volumeNfsExportContent and deletes it. Returns an error if one occurs.
func (c *FakeVolumeNfsExportContents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(volumenfsexportcontentsResource, name, opts), &volumenfsexportv1.VolumeNfsExportContent{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVolumeNfsExportContents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(volumenfsexportcontentsResource, listOpts)

	_, err := c.Fake.Invokes(action, &volumenfsexportv1.VolumeNfsExportContentList{})
	return err
}

// Patch applies the patch and returns the patched volumeNfsExportContent.
func (c *FakeVolumeNfsExportContents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *volumenfsexportv1.VolumeNfsExportContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(volumenfsexportcontentsResource, name, pt, data, subresources...), &volumenfsexportv1.VolumeNfsExportContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*volumenfsexportv1.VolumeNfsExportContent), err
}
