/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	volumenfsexportv1 "github.com/kubernetes-csi/external-nfsexporter/client/v6/apis/volumenfsexport/v1"
	versioned "github.com/kubernetes-csi/external-nfsexporter/client/v6/clientset/versioned"
	internalinterfaces "github.com/kubernetes-csi/external-nfsexporter/client/v6/informers/externalversions/internalinterfaces"
	v1 "github.com/kubernetes-csi/external-nfsexporter/client/v6/listers/volumenfsexport/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VolumeNfsExportContentInformer provides access to a shared informer and lister for
// VolumeNfsExportContents.
type VolumeNfsExportContentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.VolumeNfsExportContentLister
}

type volumeNfsExportContentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVolumeNfsExportContentInformer constructs a new informer for VolumeNfsExportContent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVolumeNfsExportContentInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVolumeNfsExportContentInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVolumeNfsExportContentInformer constructs a new informer for VolumeNfsExportContent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVolumeNfsExportContentInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NfsExportV1().VolumeNfsExportContents().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NfsExportV1().VolumeNfsExportContents().Watch(context.TODO(), options)
			},
		},
		&volumenfsexportv1.VolumeNfsExportContent{},
		resyncPeriod,
		indexers,
	)
}

func (f *volumeNfsExportContentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVolumeNfsExportContentInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *volumeNfsExportContentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&volumenfsexportv1.VolumeNfsExportContent{}, f.defaultInformer)
}

func (f *volumeNfsExportContentInformer) Lister() v1.VolumeNfsExportContentLister {
	return v1.NewVolumeNfsExportContentLister(f.Informer().GetIndexer())
}
