/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kubernetes-csi/external-nfsexporter/client/v6/apis/volumenfsexport/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VolumeNfsExportClassLister helps list VolumeNfsExportClasses.
// All objects returned here must be treated as read-only.
type VolumeNfsExportClassLister interface {
	// List lists all VolumeNfsExportClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.VolumeNfsExportClass, err error)
	// Get retrieves the VolumeNfsExportClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.VolumeNfsExportClass, error)
	VolumeNfsExportClassListerExpansion
}

// volumeNfsExportClassLister implements the VolumeNfsExportClassLister interface.
type volumeNfsExportClassLister struct {
	indexer cache.Indexer
}

// NewVolumeNfsExportClassLister returns a new VolumeNfsExportClassLister.
func NewVolumeNfsExportClassLister(indexer cache.Indexer) VolumeNfsExportClassLister {
	return &volumeNfsExportClassLister{indexer: indexer}
}

// List lists all VolumeNfsExportClasses in the indexer.
func (s *volumeNfsExportClassLister) List(selector labels.Selector) (ret []*v1.VolumeNfsExportClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.VolumeNfsExportClass))
	})
	return ret, err
}

// Get retrieves the VolumeNfsExportClass from the index for a given name.
func (s *volumeNfsExportClassLister) Get(name string) (*v1.VolumeNfsExportClass, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("volumenfsexportclass"), name)
	}
	return obj.(*v1.VolumeNfsExportClass), nil
}
