/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/kubernetes-csi/external-nfsexporter/client/v6/apis/volumenfsexport/v1"
	scheme "github.com/kubernetes-csi/external-nfsexporter/client/v6/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VolumeNfsExportsGetter has a method to return a VolumeNfsExportInterface.
// A group's client should implement this interface.
type VolumeNfsExportsGetter interface {
	VolumeNfsExports(namespace string) VolumeNfsExportInterface
}

// VolumeNfsExportInterface has methods to work with VolumeNfsExport resources.
type VolumeNfsExportInterface interface {
	Create(ctx context.Context, volumeNfsExport *v1.VolumeNfsExport, opts metav1.CreateOptions) (*v1.VolumeNfsExport, error)
	Update(ctx context.Context, volumeNfsExport *v1.VolumeNfsExport, opts metav1.UpdateOptions) (*v1.VolumeNfsExport, error)
	UpdateStatus(ctx context.Context, volumeNfsExport *v1.VolumeNfsExport, opts metav1.UpdateOptions) (*v1.VolumeNfsExport, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.VolumeNfsExport, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.VolumeNfsExportList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VolumeNfsExport, err error)
	VolumeNfsExportExpansion
}

// volumeNfsExports implements VolumeNfsExportInterface
type volumeNfsExports struct {
	client rest.Interface
	ns     string
}

// newVolumeNfsExports returns a VolumeNfsExports
func newVolumeNfsExports(c *NfsExportV1Client, namespace string) *volumeNfsExports {
	return &volumeNfsExports{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the volumeNfsExport, and returns the corresponding volumeNfsExport object, and an error if there is any.
func (c *volumeNfsExports) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.VolumeNfsExport, err error) {
	result = &v1.VolumeNfsExport{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("volumenfsexports").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VolumeNfsExports that match those selectors.
func (c *volumeNfsExports) List(ctx context.Context, opts metav1.ListOptions) (result *v1.VolumeNfsExportList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.VolumeNfsExportList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("volumenfsexports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested volumeNfsExports.
func (c *volumeNfsExports) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("volumenfsexports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a volumeNfsExport and creates it.  Returns the server's representation of the volumeNfsExport, and an error, if there is any.
func (c *volumeNfsExports) Create(ctx context.Context, volumeNfsExport *v1.VolumeNfsExport, opts metav1.CreateOptions) (result *v1.VolumeNfsExport, err error) {
	result = &v1.VolumeNfsExport{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("volumenfsexports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeNfsExport).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a volumeNfsExport and updates it. Returns the server's representation of the volumeNfsExport, and an error, if there is any.
func (c *volumeNfsExports) Update(ctx context.Context, volumeNfsExport *v1.VolumeNfsExport, opts metav1.UpdateOptions) (result *v1.VolumeNfsExport, err error) {
	result = &v1.VolumeNfsExport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("volumenfsexports").
		Name(volumeNfsExport.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeNfsExport).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *volumeNfsExports) UpdateStatus(ctx context.Context, volumeNfsExport *v1.VolumeNfsExport, opts metav1.UpdateOptions) (result *v1.VolumeNfsExport, err error) {
	result = &v1.VolumeNfsExport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("volumenfsexports").
		Name(volumeNfsExport.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeNfsExport).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the volumeNfsExport and deletes it. Returns an error if one occurs.
func (c *volumeNfsExports) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("volumenfsexports").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *volumeNfsExports) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("volumenfsexports").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched volumeNfsExport.
func (c *volumeNfsExports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VolumeNfsExport, err error) {
	result = &v1.VolumeNfsExport{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("volumenfsexports").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
