/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/kubernetes-csi/external-nfsexporter/client/v6/apis/volumenfsexport/v1"
	scheme "github.com/kubernetes-csi/external-nfsexporter/client/v6/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VolumeNfsExportClassesGetter has a method to return a VolumeNfsExportClassInterface.
// A group's client should implement this interface.
type VolumeNfsExportClassesGetter interface {
	VolumeNfsExportClasses() VolumeNfsExportClassInterface
}

// VolumeNfsExportClassInterface has methods to work with VolumeNfsExportClass resources.
type VolumeNfsExportClassInterface interface {
	Create(ctx context.Context, volumeNfsExportClass *v1.VolumeNfsExportClass, opts metav1.CreateOptions) (*v1.VolumeNfsExportClass, error)
	Update(ctx context.Context, volumeNfsExportClass *v1.VolumeNfsExportClass, opts metav1.UpdateOptions) (*v1.VolumeNfsExportClass, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.VolumeNfsExportClass, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.VolumeNfsExportClassList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VolumeNfsExportClass, err error)
	VolumeNfsExportClassExpansion
}

// volumeNfsExportClasses implements VolumeNfsExportClassInterface
type volumeNfsExportClasses struct {
	client rest.Interface
}

// newVolumeNfsExportClasses returns a VolumeNfsExportClasses
func newVolumeNfsExportClasses(c *NfsExportV1Client) *volumeNfsExportClasses {
	return &volumeNfsExportClasses{
		client: c.RESTClient(),
	}
}

// Get takes name of the volumeNfsExportClass, and returns the corresponding volumeNfsExportClass object, and an error if there is any.
func (c *volumeNfsExportClasses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.VolumeNfsExportClass, err error) {
	result = &v1.VolumeNfsExportClass{}
	err = c.client.Get().
		Resource("volumenfsexportclasses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VolumeNfsExportClasses that match those selectors.
func (c *volumeNfsExportClasses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.VolumeNfsExportClassList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.VolumeNfsExportClassList{}
	err = c.client.Get().
		Resource("volumenfsexportclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested volumeNfsExportClasses.
func (c *volumeNfsExportClasses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("volumenfsexportclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a volumeNfsExportClass and creates it.  Returns the server's representation of the volumeNfsExportClass, and an error, if there is any.
func (c *volumeNfsExportClasses) Create(ctx context.Context, volumeNfsExportClass *v1.VolumeNfsExportClass, opts metav1.CreateOptions) (result *v1.VolumeNfsExportClass, err error) {
	result = &v1.VolumeNfsExportClass{}
	err = c.client.Post().
		Resource("volumenfsexportclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeNfsExportClass).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a volumeNfsExportClass and updates it. Returns the server's representation of the volumeNfsExportClass, and an error, if there is any.
func (c *volumeNfsExportClasses) Update(ctx context.Context, volumeNfsExportClass *v1.VolumeNfsExportClass, opts metav1.UpdateOptions) (result *v1.VolumeNfsExportClass, err error) {
	result = &v1.VolumeNfsExportClass{}
	err = c.client.Put().
		Resource("volumenfsexportclasses").
		Name(volumeNfsExportClass.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeNfsExportClass).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the volumeNfsExportClass and deletes it. Returns an error if one occurs.
func (c *volumeNfsExportClasses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("volumenfsexportclasses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *volumeNfsExportClasses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("volumenfsexportclasses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched volumeNfsExportClass.
func (c *volumeNfsExportClasses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VolumeNfsExportClass, err error) {
	result = &v1.VolumeNfsExportClass{}
	err = c.client.Patch(pt).
		Resource("volumenfsexportclasses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
