/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/kubernetes-csi/external-nfsexporter/client/v6/apis/volumenfsexport/v1"
	scheme "github.com/kubernetes-csi/external-nfsexporter/client/v6/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VolumeNfsExportContentsGetter has a method to return a VolumeNfsExportContentInterface.
// A group's client should implement this interface.
type VolumeNfsExportContentsGetter interface {
	VolumeNfsExportContents() VolumeNfsExportContentInterface
}

// VolumeNfsExportContentInterface has methods to work with VolumeNfsExportContent resources.
type VolumeNfsExportContentInterface interface {
	Create(ctx context.Context, volumeNfsExportContent *v1.VolumeNfsExportContent, opts metav1.CreateOptions) (*v1.VolumeNfsExportContent, error)
	Update(ctx context.Context, volumeNfsExportContent *v1.VolumeNfsExportContent, opts metav1.UpdateOptions) (*v1.VolumeNfsExportContent, error)
	UpdateStatus(ctx context.Context, volumeNfsExportContent *v1.VolumeNfsExportContent, opts metav1.UpdateOptions) (*v1.VolumeNfsExportContent, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.VolumeNfsExportContent, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.VolumeNfsExportContentList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VolumeNfsExportContent, err error)
	VolumeNfsExportContentExpansion
}

// volumeNfsExportContents implements VolumeNfsExportContentInterface
type volumeNfsExportContents struct {
	client rest.Interface
}

// newVolumeNfsExportContents returns a VolumeNfsExportContents
func newVolumeNfsExportContents(c *NfsExportV1Client) *volumeNfsExportContents {
	return &volumeNfsExportContents{
		client: c.RESTClient(),
	}
}

// Get takes name of the volumeNfsExportContent, and returns the corresponding volumeNfsExportContent object, and an error if there is any.
func (c *volumeNfsExportContents) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.VolumeNfsExportContent, err error) {
	result = &v1.VolumeNfsExportContent{}
	err = c.client.Get().
		Resource("volumenfsexportcontents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VolumeNfsExportContents that match those selectors.
func (c *volumeNfsExportContents) List(ctx context.Context, opts metav1.ListOptions) (result *v1.VolumeNfsExportContentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.VolumeNfsExportContentList{}
	err = c.client.Get().
		Resource("volumenfsexportcontents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested volumeNfsExportContents.
func (c *volumeNfsExportContents) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("volumenfsexportcontents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a volumeNfsExportContent and creates it.  Returns the server's representation of the volumeNfsExportContent, and an error, if there is any.
func (c *volumeNfsExportContents) Create(ctx context.Context, volumeNfsExportContent *v1.VolumeNfsExportContent, opts metav1.CreateOptions) (result *v1.VolumeNfsExportContent, err error) {
	result = &v1.VolumeNfsExportContent{}
	err = c.client.Post().
		Resource("volumenfsexportcontents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeNfsExportContent).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a volumeNfsExportContent and updates it. Returns the server's representation of the volumeNfsExportContent, and an error, if there is any.
func (c *volumeNfsExportContents) Update(ctx context.Context, volumeNfsExportContent *v1.VolumeNfsExportContent, opts metav1.UpdateOptions) (result *v1.VolumeNfsExportContent, err error) {
	result = &v1.VolumeNfsExportContent{}
	err = c.client.Put().
		Resource("volumenfsexportcontents").
		Name(volumeNfsExportContent.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeNfsExportContent).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *volumeNfsExportContents) UpdateStatus(ctx context.Context, volumeNfsExportContent *v1.VolumeNfsExportContent, opts metav1.UpdateOptions) (result *v1.VolumeNfsExportContent, err error) {
	result = &v1.VolumeNfsExportContent{}
	err = c.client.Put().
		Resource("volumenfsexportcontents").
		Name(volumeNfsExportContent.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeNfsExportContent).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the volumeNfsExportContent and deletes it. Returns an error if one occurs.
func (c *volumeNfsExportContents) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("volumenfsexportcontents").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *volumeNfsExportContents) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("volumenfsexportcontents").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched volumeNfsExportContent.
func (c *volumeNfsExportContents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VolumeNfsExportContent, err error) {
	result = &v1.VolumeNfsExportContent{}
	err = c.client.Patch(pt).
		Resource("volumenfsexportcontents").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
